//
//  RepositoryModels.swift
//  CleanSwift
//
//  Created by ByoungHoon Yun on 15/06/2019.
//  Copyright (c) 2019 ByoungHoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GitHubAPI

enum Repository
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            let keyword: String
        }
        struct Response
        {
            // or json
            let listData: [GitHubRepository]
        }
        struct ViewModel
        {
            let list: [GitHubRepository]
        }
    }
}

