//
//  RepositoryWorker.swift
//  CleanSwift
//
//  Created by ByoungHoon Yun on 15/06/2019.
//  Copyright (c) 2019 ByoungHoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import GitHubAPI

class RepositoryWorker {
    
    func requestRepositories(keyword: String, completion:@escaping ([GitHubRepository])-> Void) {
        GitHubAPI.requestRepositories(keyword, completion: completion)
    }
}

