//
//  RepositoryPresenter.swift
//  CleanSwift
//
//  Created by ByoungHoon Yun on 15/06/2019.
//  Copyright (c) 2019 ByoungHoon. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol RepositoryPresentationLogic
{
    func presentSomething(response: Repository.Something.Response)
}

class RepositoryPresenter: RepositoryPresentationLogic
{
    weak var viewController: RepositoryDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Repository.Something.Response)
    {
        let viewModel = Repository.Something.ViewModel(list: response.listData)
        viewController?.displaySomething(viewModel: viewModel)
    }
}

